// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using restAPI.DataContext.Models;

namespace restAPI.Migrations
{
    [DbContext(typeof(DevicePositionContext))]
    partial class DevicePositionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("restAPI.DataContracts.DeviceMapPoint", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RecordId");

                    b.Property<ulong>("EUI")
                        .HasColumnName("eui");

                    b.Property<uint>("ID")
                        .HasColumnName("id");

                    b.Property<double>("Latitude")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitute")
                        .HasColumnName("Longitude");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnName("TimeStamp");

                    b.HasKey("RecordId");

                    b.ToTable("DeviceMapPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
